[[navigator]]
= Interacting with content

Geb provides a concise and Groovy interface to the content and controls in your browser.
This is implemented through the `Navigator` API which is a jQuery inspired mechanism for finding, filtering and interacting with DOM elements.

== The `$()` function

The `$()` function is the access point to the browser's page content.
It returns a `{navigator-api}` object that is roughly analogous to a jQuery object.
It is analogous in that it represents one or more elements on the page and can be used to refine the matched content or query the matched content.
When a `$()` function is called that does not match any content, an “empty” navigator object is returned that represents no content.
Operations on “empty” navigators return `null` or another “empty” navigator or other values that make sense (e.g. the `size()` method returns `0`).

The signature of the `$()` function is as follows…

[source,groovy]
----
$(«css selector», «index or range», «attribute / text matchers»)
----

The following is a concrete example…

[source,groovy]
----
include::{testDir}/navigator/DollarExamplesSpec.groovy[tag=concrete_example,indent=0]
----

This would find the 3rd (elements are 0 indexed) `h1` element whose `class` _attribute_ is exactly “`heading`”.

All arguments are optional, meaning the following calls are all valid:

[source,groovy]
----
include::{testDir}/navigator/DollarExamplesSpec.groovy[tag=other_examples,indent=0]
----

[NOTE]
====
There is an alias for the dollar function named “find” if a method named “$” is not to your taste.
====

=== CSS Selectors

You can use any CSS selector that the underlying `WebDriver` supports…

[source,groovy]
----
include::{testDir}/navigator/DollarExamplesSpec.groovy[tag=css3_selectors,indent=0]
----

HTMLUnit driver only partially supports CSS 3.
A future version of the HTMLUnit driver may gain better CSS 3 support.

=== Using WebDriver's `By` class selectors

For all signatures of `$()` function that accept a css selector there is an equivalent signature where an instance of WebDriver's `{by-api}` class can be used instead of a `String`.

Using CSS selectors is the idiomatic way of using Geb and should be preferred to using `By` selectors.
It is always possible to select the same elements using a css selector as when using a certain `By` selector apart from certain XPath selectors which is why this convenience mechanism is provided.

Following are some examples of using `By` selectors…

[source,groovy]
----
include::{testDir}/navigator/DollarExamplesSpec.groovy[tag=by_selectors,indent=0]
----

=== Indexes and ranges

When matching, a single positive integer or integer range can be given to restrict by index.

Consider the following html…

[source,html]
----
include::{testDir}/navigator/DollarExamplesSpec.groovy[tag=indexes_and_ranges_html,indent=0]
----

We can use indexes to match content like so…

[source,groovy]
----
include::{testDir}/navigator/DollarExamplesSpec.groovy[tag=indexes_and_ranges,indent=0]
----

See below for an explanation of the `text()` method and the use of the spread operator.

=== Attribute and text matching

Matches can be made on attributes and node text values via Groovy's named parameter syntax.
The value `text` is treated specially as a match against the node's text.
All other values are matched against their corresponding attribute values.

Consider the following html…

[source,html]
----
include::{testDir}/navigator/DollarExamplesSpec.groovy[tag=attributes_html,indent=0]
----

We can use attribute matchers like so…

[source,groovy]
----
include::{testDir}/navigator/DollarExamplesSpec.groovy[tag=attributes,indent=0]
----

Attribute values are `and`ed together…

[source,groovy]
----
include::{testDir}/navigator/DollarExamplesSpec.groovy[tag=multiple_attributes,indent=0]
----

We can use text matchers like so…

[source,groovy]
----
include::{testDir}/navigator/DollarExamplesSpec.groovy[tag=text_matchers,indent=0]
----

You can mix attribute and text matchers…

[source,groovy]
----
include::{testDir}/navigator/DollarExamplesSpec.groovy[tag=matchers_and_attributes,indent=0]
----

==== Using patterns

To match the entire value of an attribute or the text you use a `String` value. It is also possible to use a `Pattern` to do regexp matching…

[source,groovy]
----
include::{testDir}/navigator/DollarExamplesSpec.groovy[tag=pattern,indent=0]
----

Geb also ships with a bunch of shortcut pattern methods…

[source,groovy]
----
include::{testDir}/navigator/DollarExamplesSpec.groovy[tag=pattern_methods,indent=0]
----

The following is the complete listing:

|===
|Case Sensitive |Case Insensitive |Description

|`startsWith` |`iStartsWith` |Matches values that start with the given value
|`contains` |`iContains` |Matches values that contain the given value anywhere
|`endsWith` |`iEndsWith` |Matches values that end with the given value
|`containsWord` |`iContainsWord` |Matches values that contain the given value surrounded by either whitespace or the beginning or end of the value
|`notStartsWith` |`iNotStartsWith` |Matches values that DO NOT start with the given value
|`notContains` |`iNotContains` |Matches values that DO NOT contain the given value anywhere
|`notEndsWith` |`iNotEndsWith` |Matches values that DO NOT end with the given value
|`notContainsWord` |`iNotContainsWord` |Matches values that DO NOT contain the given value surrounded by either whitespace or the beginning or end of the value
|===

All of these methods themselves can take a `String` or a `Pattern`…

[source,groovy]
----
include::{testDir}/navigator/DollarExamplesSpec.groovy[tag=pattern_methods_using_pattern,indent=0]
----

[NOTE]
====
You might be wondering how this magic works, i.e. where these methods come from and where they can be used.
They are methods that are available on `geb.Page` and other _places_ where you can use the $ function.
They simply just return patterns.
====

=== Navigators are iterable

The navigator objects implement the Java `Iterable` interface, which allows you to do lots of Groovy stuff like use the `max()` function…

Consider the following html…

[source,html]
----
include::{testDir}/navigator/IterableSpec.groovy[tag=iterable_html,indent=0]
----

You can use the `max()` function on `Navigator` instances…

[source,groovy]
----
include::{testDir}/navigator/IterableSpec.groovy[tag=max,indent=0]
----

This also means that navigator objects work with the Groovy spread operator…

[source,groovy]
----
include::{testDir}/navigator/IterableSpec.groovy[tag=spread,indent=0]
----

When treating a navigator as `Iterable`, the iterated over content is always the exact matched elements (as opposed to including children).

=== `equals()` and `hashCode()`

It's possible to check `Navigator` instances for equality.
The rules are simple - two empty navigators are always equal and two non empty navigators are only equal if they contain the exact same elements in the same order.

Consider the following HTML…

[source,html]
----
include::{testDir}/navigator/EqualsSpec.groovy[tag=html,indent=0]
----

Here are some examples of equal Navigator instances…

[source,groovy]
----
include::{testDir}/navigator/EqualsSpec.groovy[tag=equal,indent=0]
----
<1> Two empty navigators
<2> Two single element navigators containing the same element
<3> Two single element navigators containing the same element created using different methods
<4> Two multi element navigators containing the same elements
<5> Two multi element navigators containing the same elements created using different methods

And some that are not equal…

[source,groovy]
----
include::{testDir}/navigator/EqualsSpec.groovy[tag=not_equal,indent=0]
----
<1> Empty and not empty navigators
<2> Single element navigators containing different elements
<3> Multi element navigators containing the same elements but in a different order

== Finding &amp; filtering

Navigator objects have `find()` and `$()` methods for finding descendants, and `filter()` and `not()` methods for reducing the matched content.

Consider the following HTML…

[source,html]
----
include::{testDir}/navigator/FindingAndFilteringSpec.groovy[tag=html,indent=0]
----

We can select `p.b` by…

[source,groovy]
----
include::{testDir}/navigator/FindingAndFilteringSpec.groovy[tag=find,indent=0]
include::{testDir}/navigator/FindingAndFilteringSpec.groovy[tag=dollar,indent=0]
----

We can select `div.b` by…

[source,groovy]
----
include::{testDir}/navigator/FindingAndFilteringSpec.groovy[tag=filter,indent=0]
----

or…

[source,groovy]
----
include::{testDir}/navigator/FindingAndFilteringSpec.groovy[tag=not,indent=0]
----

We can select the `div` containing the `p` with…

[source,groovy]
----
include::{testDir}/navigator/FindingAndFilteringSpec.groovy[tag=a_has,indent=0]
----

Or select the `div` containing the `input` with a type attribute of "text" like so…

[source,groovy]
----
include::{testDir}/navigator/FindingAndFilteringSpec.groovy[tag=b_has,indent=0]
----

We can select the `div` that does not contain the `p` with…

[source,groovy]
----
include::{testDir}/navigator/FindingAndFilteringSpec.groovy[tag=b_has_not,indent=0]
----

Or select the `div` that does not contain the `input` with a type attribute of "text" like so…

[source,groovy]
----
include::{testDir}/navigator/FindingAndFilteringSpec.groovy[tag=a_has_not,indent=0]
----

Or select the two `div` that do not contain `input` with a type attribute of "submit" like so…

[source,groovy]
----
include::{testDir}/navigator/FindingAndFilteringSpec.groovy[tag=has_not,indent=0]
----

The `find()` and `$()` methods support the *exact same argument types as the `$()` function*.

The `filter()`, `not()`, `has()` and `hasNot()` methods have the same signatures - they accept: a selector string, a predicates map or both.

These methods return a new navigator object that represents the new content.

== Composition

It is also possible to compose navigator objects from other navigator objects, for situations where you can't express a content set in one query.
To do this, simply call the `$()` function and pass in the navigators to compose.

Consider the following markup…

[source,html]
----
include::{testDir}/navigator/CompositionSpec.groovy[tag=html,indent=0]
----

You can then create a new navigator object that represents both the `a` and `b` paragraphs the following way:

[source,groovy]
----
include::{testDir}/navigator/CompositionSpec.groovy[tag=dollar,indent=0]
----

An alternative way is to use the `add()` method of `Navigator` that takes either a `String` or a Webdriver's `By` selector:

[source,groovy]
----
include::{testDir}/navigator/CompositionSpec.groovy[tag=add,indent=0]
----

Finally, you can compose navigator objects from content. So given a page content definition:

[source,groovy]
----
include::{testDir}/navigator/CompositionSpec.groovy[tag=content_definition,indent=0]
----

You can compose content elements into a navigator in the following way:

[source,groovy]
----
include::{testDir}/navigator/CompositionSpec.groovy[tag=content,indent=0]
----

== Traversing

Navigators also have methods for selecting content _around_ the matched content.

Consider the following HTML…

[source,html]
----
include::{testDir}/navigator/TraversingSpec.groovy[tag=siblings_html,indent=0]
----

You can select content _around_ `p.d` by…

[source,groovy]
----
include::{testDir}/navigator/TraversingSpec.groovy[tag=siblings,indent=0]
----

Consider the following HTML…

[source,html]
----
include::{testDir}/navigator/TraversingSpec.groovy[tag=next_html,indent=0]
----

The following code will select `p.b` &amp; `p.c`…

[source,groovy]
----
include::{testDir}/navigator/TraversingSpec.groovy[tag=next,indent=0]
----

The `previous()`, `prevAll()`, `next()`, `nextAll()`, `parent()`, `parents()`, `closest()`, `siblings()` and `children()` methods can also take CSS selectors and attribute matchers.

Using the same html, the following examples will select `p.c`…

[source,groovy]
----
include::{testDir}/navigator/TraversingSpec.groovy[tag=next_with_args,indent=0]
----

Likewise, consider the following HTML…

[source,html]
----
include::{testDir}/navigator/TraversingSpec.groovy[tag=parent_closest_html,indent=0]
----

The following examples will select `div.b`…

[source,groovy]
----
include::{testDir}/navigator/TraversingSpec.groovy[tag=parent,indent=0]
----

The `closest()` method is a special case in that it will select the first ancestor of the current elements that matches a selector.
There is no no-argument version of the `closest()` method.
For example, these will select `div.a`…

[source,groovy]
----
include::{testDir}/navigator/TraversingSpec.groovy[tag=closest,indent=0]
----

These methods do not take indexes as they automatically select the first matching content.
To select multiple elements you can use `prevAll()`, `nextAll()` and `parents()` all of which have no-argument versions and versions that filter by a selector.

The `nextUntil()`, `prevUntil()` and `parentsUntil()` methods return all nodes along the relevant axis _until_ the first one that matches a selector or attributes.
Consider the following markup:

[source,html]
----
include::{testDir}/navigator/TraversingSpec.groovy[tag=next_until_html,indent=0]
----

The following examples will select `div.b` and `div.c`:

[source,groovy]
----
include::{testDir}/navigator/TraversingSpec.groovy[tag=next_until,indent=0]
----

== Clicking

Navigator objects implement the `click()` method, which will instruct the browser to click *only the first item* the navigator has matched.

There are also `click(Class)` , `click(Page)` and `click(List)` methods that are analogous to the browser object's
<<changing-pages,`page(Class&lt;? extends Page&gt;)`, `page(Page)`, and `page(Class&lt;? extends Page&gt;[])`, `page(Page[])` methods respectively>>.
This allow page changes to be specified at the same time as click actions.

For example…

[source,groovy]
----
include::{testDir}/navigator/ClickingSpec.groovy[tag=click,indent=0]
----

Would click the `a.login` element, then effectively call `browser.page(LoginPage)` and verify that the browser is at the expected page.

All of the page classes passed in when using the list variant have to have an “at” checker defined, otherwise an `UndefinedAtCheckerException` will be thrown.

== Determining visibility

Navigator objects have a `displayed` property that indicates whether the element is visible to the user or not.
The `displayed` property of a navigator object that doesn't match anything is always `false`.

== Size and location

You can obtain the size and location of content on the page.
All units are in pixels.
The size is available via the `height` and `width` properties, while the location is available as the `x` and `y` properties which represent the distance from the top left of the page
(or parent frame) to the top left point of the content.

All of these properties operate on the *first* matched element only.

Consider the following html…

[source,html]
----
include::{testDir}/navigator/SizeAndLocationSpec.groovy[tag=html,indent=0]
----

The following conditions are satisfied for it…

[source,groovy]
----
include::{testDir}/navigator/SizeAndLocationSpec.groovy[tag=single_element,indent=0]
----

To obtain any of the properties for all matched elements, you can use the Groovy spread operator.

[source,groovy]
----
include::{testDir}/navigator/SizeAndLocationSpec.groovy[tag=multiple_elements,indent=0]
----

== Accessing tag name, attributes, text and classes

The `tag()`, `text()` and `classes()` methods as well as accessing attributes via the `@` notation return the requested content on the *first* matched content.
The `classes()` method returns a `java.util.List` of unique class names sorted alphabetically.

Consider the following HTML…

[source,html]
----
include::{testDir}/navigator/TagTextClassesAttributesSpec.groovy[tag=html,indent=0]
----

The following assertions are valid…

[source,groovy]
----
include::{testDir}/navigator/TagTextClassesAttributesSpec.groovy[tag=single_element,indent=0]
----

To obtain information about all matched content, you use the Groovy _spread operator_…

[source,groovy]
----
include::{testDir}/navigator/TagTextClassesAttributesSpec.groovy[tag=multiple_elements,indent=0]
----

== CSS properties

Css properties of a navigator can be accessed using the `css()` method.

Consider the following HTML…

----
<div style="float: left">text</div>
----

You can obtain value of the `float` css property in the following way…

----
$("div").css("float") == "left"
----

____

There are some limitations when it comes to retrieving css properties of `Navigator` objects. Color values should be returned as rgba strings, so, for example if the `background-color` property is set as `green` in the HTML source, the returned value will be `rgba(0, 255, 0, 1)`. Note that shorthand CSS properties (e.g. `background`, `font`, `border`, `border-top`, `margin`, `margin-top`, `padding`, `padding-top`, `list-style`, `outline`, `pause`, `cue`) are not returned, in accordance with the DOM CSS2 specification - you should directly access the longhand properties (e.g. `background-color`) to access the desired values.

____

== Sending keystrokes

Keystrokes can be sent to any content via the leftShift operator, which is a shortcut for the http://selenium.googlecode.com/svn/trunk/docs/api/java/org/openqa/selenium/WebElement.html#sendKeys(java.lang.CharSequence...)[`sendKeys()`] method of WebDriver.

----
$("div") << "abc"
----

How content responds to the keystrokes depends on what the content is.

:numbered!:

=== Non characters (e.g. delete key)

It is possible to send non-textual characters to content by using the WebDriver http://selenium.googlecode.com/svn/trunk/docs/api/java/org/openqa/selenium/Keys.html[Keys] enumeration…

----
import org.openqa.selenium.Keys

$("input", name: "firstName") << Keys.chord(Keys.CONTROL, "c")
----

Here we are sending a “control-c” to an input.

See the documentation for http://selenium.googlecode.com/svn/trunk/docs/api/java/org/openqa/selenium/Keys.html[Keys] for more information on the possible keys.

:numbered:

== Accessing input values

The value of `input`, `select` and `textarea` elements can be retrieved and set with the `value` method. Calling `value()` with no arguments will return the String value of _the first_ element in the Navigator. Calling `value(value)` will set the current value of _all_ elements in the Navigator. The argument can be of any type and will be coerced to a `String` if necessary. The exceptions are that when setting a `checkbox` value the method expects a `boolean` (or, an existing checkbox value) and when setting a multiple `select` the method expects an array or Collection of values.

== Form control shortcuts

Interacting with form controls (`input`, `select` etc.) is such a common task in web functional testing that Geb provides convenient shortcuts for common functions.

Geb supports the following shortcuts for dealing with form controls.

Consider the following HTML…

----
<form>
    <input type="text" name="geb" value="testing" />
</form>
----

The value can be read and written via property notation…

----
$("form").geb == "testing"
$("form").geb = "goodness"
$("form").geb == "goodness"
----

These are literally shortcuts for…

----
$("form").find("input", name: "geb").value() == "testing"
$("form").find("input", name: "geb").value("goodness")
$("form").find("input", name: "geb").value() == "goodness"
----

There is also a shortcut for obtaining a navigator based on a control name

----
$("form").geb()
----

Which is literally a shortcut for…

----
$("form").find("input", name: "geb")
----

____

In the above and below examples with form controls we are using code like `$(&quot;form&quot;).someInput` where we could be using just `someInput` as long as there is only one control with the _name_ `someInput` on the page. In the examples we are using `$(&quot;form&quot;).someInput` to hopefully be clearer.

____

If your content definition (either a page or a module) describes content which is an `input`, `select` or `textarea`, you can access and set its value the same way as described above for forms. Given a page and module definitions for the above mentioned HTML:

----
class ShortcutModule extends Module {
    static content = {
        geb { $('form').geb() }
    }
}

static content = {
    geb { $('form').geb() }
    shortcutModule { module ShortcutModule }
}
----

The following will pass:

----
assert geb == "testing"
geb = "goodness"
assert geb == "goodness"
----

As well as:

----
assert shortcutModule.geb == "testing"
shortcutModule.geb = "goodness"
assert shortcutModule.geb == "goodness"
----

____

The following examples describe usage of form controls only using code like `$(&quot;form&quot;).someInput`. Given a content definition `myContent { $(&quot;form&quot;).someInput }`, you can substitute `$(&quot;form&quot;).someInput` in the examples with `myContent`.

____

== Setting form control values

____

Trying to set a value on an element which is not one of `input`, `select` or `textarea` will cause an `UnableToSetElementException` to be thrown.

____

=== Select

Select values are set by assigning the value or text of the required option. Assigned values are automatically coerced to String. For example…

----
<select name="artist">
    <option value="1">Ima Robot</option>
    <option value="2">Edward Sharpe and the Magnetic Zeros</option>
    <option value="3">Alexander</option>
</select>
----

We can select options with…

----
$("form").artist = "1"         // first option selected by its value attribute
$("form").artist = 2           // second option selected by its value attribute
$("form").artist = "Ima Robot" // first option selected by its text
----

If you attempt to set a select to a value that does not match the value or text of any options, an `IllegalArgumentException` will be thrown.

=== Multiple select

If the select has the `multiple` attribute it is set with a array or `Collection` of values. Any options not in the values are un-selected. For example…

----
<select name="genres" multiple>
    <option value="1">Alt folk</option>
    <option value="2">Chiptunes</option>
    <option value="3">Electroclash</option>
    <option value="4">G-Funk</option>
    <option value="5">Hair metal</option>
</select>
----

We can select options with…

----
$("form").genres = ["2", "3"]                 // second and third options selected by their value attributes
$("form").genres = [1, 4, 5]                  // first, fourth and fifth options selected by their value attributes
$("form").genres = ["Alt folk", "Hair metal"] // first and last options selected by their text
$("form").genres = []                         // all options un-selected
----

If the collection being assigned contains a value that does not match the value or text of any options, an `IllegalArgumentException` will be thrown.

=== Checkbox

Checkboxes are generally checked/unchecked by setting their value to `true` or `false`.

You can also check a checkbox by explicitly setting its `value`. This is useful when you have a number of checkboxes with the same name, i.e.

----
<input type="checkbox" name="pet" value="dogs" />
<input type="checkbox" name="pet" value="cats" />
----

You can select dogs as your pet type, as follows:

----
$("input", type: "checkbox", name: "pet").value("dogs")
----

Calling `value()` on a checked checkbox will return the value of its `value` attribute, i.e:

----
<input type="checkbox" name="pet" value="dogs" checked="checked"/>

assert $("input", type: "checkbox", name: "pet").value() == "dogs"
----

Calling `value()` on an unchecked checkbox will return `false`, i.e:

----
<input type="checkbox" name="pet" value="dogs"/>

assert $("input", type: "checkbox", name: "pet").value() == false
----

In general you should use [Groovy Truth][groovy-truth] when checking if a checkbox is checked:

----
if ($("input", type: "checkbox", name: "pet").value()) {
    //evaluated only if "pet" checkbox is checked
}
----

=== Radio

Radio values are set by assigning the value of the radio button that is to be selected or the label text associated with a radio button.

For example, with the following radio buttons…

----
<label for="site-current">Search this site</label>
<input type="radio" id="site-current" name="site" value="current">

<label>Search Google
    <input type="radio" name="site" value="google">
</label>
----

We can select the radios with…

----
$("form").site = "current"          // selects the first radio by its value
$("form").site = "Search this site" // selects the first radio by its label
$("form").site = "Search Google"    // selects the second radio by its label
----

=== Text inputs and textareas

In the case of a text `input`, the assigned value becomes the input's _value_ attribute and for a `textarea` effectively becomes the text.

It is also possible to append text by using the send keys shorthand…

----
<input name="language" value="gro" />

$("form").language() << "ovy"
assert $("form").language == "groovy"
----

Which an also be used for non-character keys…

----
<input name="postcode" />

import org.openqa.selenium.Keys

$("form").postcode = "12345"
$("form").postcode() << Keys.BACK_SPACE
assert $("form").postcode == "1234"
----

____

Note that WebDriver has some issues with textareas and surrounding whitespace. Namely, some drivers implicitly trim whitespace from the beginning and end of the value. You can track this issue here: http://code.google.com/p/selenium/issues/detail?id=2131

____

=== File upload

It's currently not possible with WebDriver to simulate the process of a user clicking on a file upload control and choosing a file to upload via the normal file chooser. However, you can directly set the value of the upload control to the _absolute path_ of a file on the system where the driver is running and on form submission that file will be uploaded.

----
<input type="file" name="csvFile">

$("form").csvFile = "/path/to/my/file.csv"
----

== Complex interactions

WebDriver supports interactions that are more complex than simply clicking or typing into items, such as dragging. You can use this API from Geb, or use the more Geb friendly `interact {}` DSL (explained below).

=== Using the WebDriver API directly

A Geb navigator object is built on top of a collection of WebDriver [WebElement][webelement-api] objects. It is possible to access the contained `WebElement`s via the following methods on navigator objects:

----
WebElement firstElement()
WebElement lastElement()
Collection<WebElement> allElements()
----

By using the methods of the WebDriver http://selenium.googlecode.com/svn/trunk/docs/api/java/org/openqa/selenium/interactions/Actions.html[Actions] class with WebElements, complex user gestures can be emulated.

=== Using `Actions`

Create an Actions instance after obtaining the WebDriver driver:

----
def actions = new Actions(driver)
----

Next, use methods of Actions to compose a series of UI actions, then call build() to create a concrete Action:

----
import org.openqa.selenium.Keys

WebElement someItem = $('li.clicky').firstElement()
def shiftDoubleClickAction = actions.keyDown(Keys.SHIFT).doubleClick(someItem).keyUp(Keys.SHIFT).build()
----

Finally, call perform() to actually trigger the desired mouse or keyboard behavior:

----
shiftDoubleClickAction.perform()
----

=== Using interact closures

To cut down on the amount of typing required, use an interact closure instead of using class `Actions` explicitly. When using an interact closure, an `Actions` instance is implicitly created, built into an Action, and performed. As an added bonus, Geb navigators can be passed directly to `Actions` methods within an interact closure.

This interact closure performs the same work as the calls in the 'Using Actions' section:

----
import org.openqa.selenium.Keys

interact {
    keyDown(Keys.SHIFT)
    doubleClick($('li.clicky'))
    keyUp(Keys.SHIFT)
}
----

This method creates code that is more readable than using `Actions` directly.

For the full list of available interactions, see the documentation for the WebDriver http://selenium.googlecode.com/svn/trunk/docs/api/java/org/openqa/selenium/interactions/Actions.html[Actions] class.

=== Interact examples

Interact closures (or Actions) can be used to perform behaviors that are more complicated than clicking buttons and anchors or typing in input fields. Shift-double-clicking was demonstrated earlier.

==== Drag and drop

clickAndHold, moveByOffset, and then release will drag and drop an element on the page.

----
interact {
    clickAndHold($('#element'))
    moveByOffset(400, -150)
    release()
}
----

Drag-and-dropping can also be accomplished using the `dragAndDropBy` convenience method from the Actions API:

----
interact {
    dragAndDropBy($('#element'), 400, -150)
}
----

In this particular example, the element will be clicked then dragged 400 pixels to the right and 150 pixels upward before being released.

____

Note that moving to arbitrary locations with the mouse is currently not supported by the HTMLUnit driver, but moving directly to elements is.

____

==== Control-clicking

Control-clicking several elements, such as items in a list, is performed the same way as shift-clicking.

----
import org.openqa.selenium.Keys

interact {
    keyDown(Keys.CONTROL)
    click($('ul.multiselect li', text: 'Order 1'))
    click($('ul.multiselect li', text: 'Order 2'))
    click($('ul.multiselect li', text: 'Order 3'))
    keyUp(Keys.CONTROL)
}
----