[[modules]]
= Modules

Modules are re-usable definitions of content that can be used across multiple pages.
They are useful for modelling things like UI widgets that are used across multiple pages, or even for defining more complex UI elements in a page.

They are defined in a manner similar to pages, but extend `{module-api}`…

[source,groovy]
----
include::{test-dir}/modules/FormContentSpec.groovy[tag=form_module,indent=0]
----

Pages can “include” modules using the following syntax…

[source,groovy]
----
include::{test-dir}/modules/IntroductionSpec.groovy[tag=module_page,indent=0]
----

The `module` method returns an instance of a module class which can then be used in the following way…

[source,groovy]
----
include::{test-dir}/modules/IntroductionSpec.groovy[tag=using_modules,indent=0]
----

Modules can also be parameterised…

[source,groovy]
----
include::{test-dir}/modules/IntroductionSpec.groovy[tag=parameterized_module,indent=0]
----

Where the parameters are passed to constructor of the module…

[source,groovy]
----
include::{test-dir}/modules/IntroductionSpec.groovy[tag=parameterized_module_page,indent=0]
----

[source,groovy]
----
include::{test-dir}/modules/IntroductionSpec.groovy[tag=using_parameterized_modules,indent=0]
----

Modules can also include other modules…

[source,groovy]
----
include::{test-dir}/modules/IntroductionSpec.groovy[tag=outer_module_and_page,indent=0]
----

[source,groovy]
----
include::{test-dir}/modules/IntroductionSpec.groovy[tag=using_nested_modules,indent=0]
----

== Base And context

Modules can be localised to a specific section of the page that they are used in, or they can specify an absolute context as part of their definition.
There are two ways that a modules base/context can be defined.

Module can be based on a `Navigator` instance…

[source,groovy]
----
include::{test-dir}/modules/FormContentSpec.groovy[tag=form_module,indent=0]

include::{test-dir}/modules/BaseAndContextSpec.groovy[tag=module_with_base_page,indent=0]
----

[source,groovy]
----
include::{test-dir}/modules/BaseAndContextSpec.groovy[tag=using_module_with_dynamic_base,indent=0]
----

It can also be done outside of a content definition…

[source,groovy]
----
include::{test-dir}/modules/BaseAndContextSpec.groovy[tag=creating_module_inline,indent=0]
----

We can define a `Navigator` context when including the module using the above syntax.
This now means that calls to _all_ `Navigator` (e.g. `$()`) method calls that occur within the module are against the given context (in this case, the `form` element).

However, module classes can also define their own base…

[source,groovy]
----
include::{test-dir}/modules/BaseAndContextSpec.groovy[tag=form_module_with_base,indent=0]
----

[source,groovy]
----
include::{test-dir}/modules/BaseAndContextSpec.groovy[tag=using_module_with_static_base,indent=0]
----

Basing a module on a `Navigator` and defining a base in a module can be combined. Consider the following HTML…

[source,html]
----
include::{test-dir}/modules/CombinedModuleBaseSpec.groovy[tag=html,indent=0]
----

And the following content definitions…

[source,groovy]
----
include::{test-dir}/modules/CombinedModuleBaseSpec.groovy[tag=content,indent=0]
----

Then they can be used in the following way…

[source,groovy]
----
include::{test-dir}/modules/CombinedModuleBaseSpec.groovy[tag=example,indent=0]
----

If the module declares a base, it is always calculated _relative_ to the `Navigator` used in the initialization statement.
If the initialization statement does not use a `Navigator`, the module's base is calculated relative to the document root.

== `Module` is-a `Navigator`

Modules always have a base navigator associated with them (if you don't specify a base for a module at all then it will be assigned the root element of the document as the base) so it is natural to
think of them as navigators.
Keeping in mind that `Module` implements `Navigator` and considering the following HTML…

[source,html]
----
include::{test-dir}/modules/ModuleIsANavigatorSpec.groovy[tag=html,indent=0]
----

As well as these content definitions…

[source,groovy]
----
include::{test-dir}/modules/ModuleIsANavigatorSpec.groovy[tag=content,indent=0]
----

The following will pass…

[source,groovy]
----
include::{test-dir}/modules/ModuleIsANavigatorSpec.groovy[tag=on_module,indent=0]
----

It's also possible to use `Navigator` methods inside of a module implementation…

[source,groovy]
----
include::{test-dir}/modules/ModuleIsANavigatorSpec.groovy[tag=in_module_definition,indent=0]
----

[source,groovy]
----
include::{test-dir}/modules/ModuleIsANavigatorSpec.groovy[tag=in_module,indent=0]
----

== Reusing modules across pages

As previously stated, modules can be used to model page fragments that are reused across multiple pages.
For example, many different types of pages in your application may show information about the user's shopping cart.
You could handle this with modules…

[source,groovy]
----
include::{test-dir}/modules/ReusingModulesSpec.groovy[tag=content,indent=0]
----

Modules work well for this.

== Using modules for repeating content

Other than content that is repeated on different pages (like the shopping cart mentioned above), pages also can have content that is repeated on the page itself.
On a checkout page, the contents of the shopping cart could be summarized with the product name, the quantity and price for each product contained.
Thanks to `Navigator` implementing `Iterable<Navigator>` a list of modules can be collected using Groovy's `collect()` and the `Navigator.module()` method.

Consider the following HTML for our cart contents:

[source,html]
----
include::{test-dir}/modules/RepeatingContentSpec.groovy[tag=html,indent=0]
----

We can model one line of the table like this:

[source,groovy]
----
include::{test-dir}/modules/RepeatingContentSpec.groovy[tag=module,indent=0]
----

And define a list of CartRows in our Page:

[source,groovy]
----
include::{test-dir}/modules/RepeatingContentSpec.groovy[tag=page,indent=0]
----

[TIP]
====
It's possible to make the creation of a list of modules from a `Navigator` even more concise by using the spread-dot operator (i.e. `$("table tr").tail()*.module(CartRow)`).
Be careful though, because it won't do what you'd expect it to do if you use this technique together with the `module()` method that takes a module instance.
Instead of creating multiple module instances like when spreading a `module()` call that takes a class it will take the single instance passed to it and initialize it multiple times returning a list
which will contain the same module instance multiple times!
====

Because the return value of `cartItems` is a list of CartRow instances, we can use any of the usual collection methods:

[source,groovy]
----
include::{test-dir}/modules/RepeatingContentSpec.groovy[tag=collection,indent=0]
----

We can also access the cart items using subscript operator together with an index or a range of indexes:

[source,groovy]
----
include::{test-dir}/modules/RepeatingContentSpec.groovy[tag=indexing,indent=0]
----

Keep in mind that you can use parametrized module instances to create lists of modules for repeating content:

[source,groovy]
----
include::{test-dir}/modules/RepeatingContentSpec.groovy[tag=parameterized_module,indent=0]
----

== The content DSL

The Content DSL used for modules is _exactly_ the same as the <<content-dsl, one used for pages>>, so all of the same options and techniques can be used.

== Inheritance

Modules can use inheritance in the <<pages-inheritance, same way that pages can>>.
That is, their content definitions are merged with any content redefined in the subclass taking precedence of the superclass.