[[testing]]
= Testing

Geb provides first class support for functional web testing via integration with popular testing frameworks such as {spock}, {junit}, {testng} and {cucumber-jvm}.

== Spock, JUnit &amp; TestNG

The Spock, JUnit and TestNG integrations work fundamentally the same way.
They provide subclasses that setup a `{browser-api}` instance that all method calls and property accesses/references resolve against via Groovy's `methodMissing` and `propertyMissing` mechanism.

[TIP]
====
Recall that the browser instance also forwards any method calls or property accesses/references that it can't handle to its current page object, which helps to remove a lot of noise from the test.
====

Consider the following Spock spec…

[source,groovy]
----
include::{test-dir}/testing/FunctionalSpec.groovy[tag=concise,indent=0]
----

Which is equivalent to…

[source,groovy]
----
include::{test-dir}/testing/FunctionalSpec.groovy[tag=verbose,indent=0]
----

=== Configuration

The browser instance is created by the testing integrations. The <<configuration, configuration mechanism>> allows you to control aspects such as the driver implementation and base URL.

[[testing-reporting]]
=== Reporting

The Spock, JUnit and TestNG integrations also ship a superclass (the name of the class for each integration module is provided below) that automatically takes reports at the end of test methods with
the label “end”.
They also set the <<report-group, report group>> to the name of the test class (substituting “.” with “/”).

The `{browser-report-method-api}` browser method is replaced with a specialised version.
This method works the same as the browser method, but adds counters and the current test method name as prefixes to the given label.

[source,groovy]
----
package my.tests

include::{test-dir}/testing/ReportingFunctionalSpec.groovy[tag=example,indent=0]
----
<1> Take a report of the login screen.

Assuming a configured `reportsDir` of `reports/geb` and the default reporters (i.e. `{screenshot-reporter-api}` and `{page-source-reporter-api}`), we would find the following files:

* `reports/geb/my/tests/ReportingFunctionalSpec/001-001-login-login screen.html`
* `reports/geb/my/tests/ReportingFunctionalSpec/001-001-login-login screen.png`
* `reports/geb/my/tests/ReportingFunctionalSpec/001-002-login-end.html`
* `reports/geb/my/tests/ReportingFunctionalSpec/001-002-login-end.png`

The report file name format is:

----
«test method number»-«report number in test method»-«test method name»-«label».«extension»
----

Reporting is an extremely useful feature and can help you diagnose test failures much easier.
Wherever possible, favour the use of the auto-reporting base classes.

[[cookie-management-in-tests]]
=== Cookie management

The Spock, JUnit and TestNG integrations will automatically clear the browser's cookies at the end of each test method.
For JUnit 3 this happens in the `tearDown()` method in `geb.junit3.GebTest`, for JUnit 4 it happens in an `@After` method in `geb.junit4.GebTest` and for TestNG it happens in an `@AfterMethod` method
in `geb.testng.GebTestTrait`.

The `geb.spock.GebSpec` class will clear the cookies in the `cleanup()` method unless the spec is `@Stepwise`, in which case they are cleared in `cleanupSpec()` (meaning that all feature methods in a
stepwise spec share the same browser state).

This auto-clearing of cookies can be <<auto-clearing-cookies-configuration, disabled via configuration>>.

=== JAR and class names

The following table illustrates the specific JARs and class names for various test frameworks that Geb integrates with.

|===
|Framework |JAR |Base Class / Trait |Reporting Base Class / Trait

|Spock |http://mvnrepository.com/artifact/{geb-group}/geb-spock[geb-spock] |link:api/geb/spock/GebSpec.html[`geb.spock.GebSpec`] |link:api/geb/spock/GebReportingSpec.html[`geb.spock.GebReportingSpec`]
|JUnit 4 |http://mvnrepository.com/artifact/{geb-group}/geb-junit4[geb-junit4] |link:api/geb/junit4/GebTest.html[`geb.junit4.GebTest`] |link:api/geb/junit4/GebReportingTest.html[`geb.junit4.GebReportingTest`]
|JUnit 3 |http://mvnrepository.com/artifact/{geb-group}/geb-junit3[geb-junit3] |link:api/geb/junit3/GebTest.html[`geb.junit3.GebTest`] |link:api/geb/junit3/GebReportingTest.html[`geb.junit3.GebReportingTest`]
|TestNG |http://mvnrepository.com/artifact/{geb-group}/geb-testng[geb-testng] |link:api/geb/testng/GebTestTrait.html[`geb.testng.GebTestTrait`] |link:api/geb/testng/GebReportingTestTrait.html[`geb.testng.GebReportingTestTrait`]
|===

=== Example projects

The following projects can be used as starting references:

* link:https://github.com/geb/geb-example-gradle[geb-example-gradle]

[[cucumber-jvm]]
== Cucumber (Cucumber-JVM)

It is possible to both:

* Write your own {cucumber-jvm} steps that manipulate Geb
* Use a library of pre-built steps that drives Geb to do many common tasks

=== Writing your own steps

Use Geb's <<binding, binding management features>> to bind a browser in before / after hooks, often in a file named `env.groovy`:

[source,groovy]
----
def bindingUpdater
Before() { scenario ->
    bindingUpdater = new BindingUpdater(binding, new Browser())
    bindingUpdater.initialize()
}

After() { scenario ->
    bindingUpdater.remove()
}
----

Then normal Geb commands and objects are available in your Cucumber steps:

[source,groovy]
----
import static cucumber.api.groovy.EN.*

Given(~/I am on the DuckDuckGo search page/) { ->
    to DuckDuckGoHomePage
    waitFor { at(DuckDuckGoHomePage) }
}

When(~/I search for "(.*)"/) { String query ->
    page.search.value(query)
    page.searchButton.click()
}

Then(~/I can see some results/) { ->
    assert at(DuckDuckGoResultsPage)
}

Then(~/the first link should be "(.*)"/) { String text ->
    waitFor { page.results }
    assert page.resultLink(0).text()?.contains(text)
}
----

=== Using pre-built steps

The {geb-cucumber} project has a set of pre-built cucumber steps that drive Geb. So for example a feature with steps similar to the above would look like:

----
When I go to the duck duck go home page
And I enter "cucumber-jvm github" into the search field
And I click the search button
Then the results table 1st row link matches /cucumber\/cucumber-jvm · GitHub.*/
----

See {geb-cucumber} for more examples.

geb-cucumber also does Geb binding automatically, so if it is picked up you don't need to do it yourself as above.

=== Example project

The following project has examples of both writing your own steps and using geb-cucumber:

* link:https://github.com/geb/geb-example-cucumber-jvm[geb-example-cucumber-jvm]
