= About the project

The Geb home page can be found at http://www.gebish.org.

== API reference

The API reference can be found link:api/index.html[here].

== Support &amp; development

Support for Geb is offered on the link:mailto:geb-user@googlegroups.com[geb-user@googlegroups.com] mailing list, which can be subscribed to https://groups.google.com/forum/#!forum/geb-user[here].

Ideas and new features for Geb can be discussed on the link:mailto:geb-dev@googlegroups.com[geb-dev@googlegroups.com] mailing list, which can be subscribed to https://groups.google.com/d/forum/geb-dev[here].

== Credits

=== Committers

* http://ldaley.com[Luke Daley]
* http://blog.proxerd.pl[Marcin Erdmann]
* github-profile:chris-prior[Chris Prior]

=== Contributors

* http://adhockery.blogspot.com/[Robert Fletcher]
* http://pniederw.wordpress.com/[Peter Niederwieser]
* github-profile:zolotov[Alexander Zolotov] - TestNG Integration
* http://c089.wordpress.com/[Christoph Neuroth] - Various fixes and patches
* http://www.desirableobjects.co.uk/[Antony Jones] - Various fixes and patches, doc improvements
* github-profile:hennr[Jan-Hendrik Peters] - Doc improvements
* http://fbflex.wordpress.com/[Tomás Lin] - Doc improvements
* github-profile:measlyweasel[Jason Cahoon] - Bug fix around text matchers
* http://refaktor.blogspot.com/[Tomasz Kalkosiński] - Doc improvements
* github-profile:richdouglasevans[Rich Douglas Evans] - Doc improvements
* github-profile:idurkan[Ian Durkan] - Doc improvements
* github-profile:ColinHarrington[Colin Harrington] - Doc improvements
* github-profile:bherrmann7[Bob Herrmann] - Doc improvements
* github-profile:walterg2[George T Walters II] - Page option support for `withWindow()`
* github-profile:craigatk[Craig Atkinson] - Doc improvements
* github-profile:andyjduncan[Andy Duncan] - Fail fast when unexpected pages are encountered
* github-profile:johnrengelman[John Engelman] - Grails integration improvements
* github-profile:legart[Michael Legart] - Grails integration improvements
* github-profile:graemerocher[Graeme Rocher] - Grails integration improvements
* github-profile:craigatk[Craig Atkinson] - Bug fix around unexpected pages
* github-profile:kgeis[Ken Geis] - Doc improvements
* github-profile:kellyrob99[Kelly Robinson] - Additional configuration parameters for SauceLabs
* github-profile:tygerpatch[Todd Gerspacher] - Doc improvements, Cleaned up settings.gradle
* github-profile:davidmc24[David M. Carr] - BrowserStack integration
* github-profile:tomdcc[Tom Dunstan] - Cucumber integration and related documentation
* github-profile:brian428[Brian Kotek] - Doc improvements
* github-profile:david-w-millar[David W Millar] - Doc improvements
* github-profile:alincode[Ai-Lin Liou] - Doc improvements
* github-profile:menonvarun[Varun Menon] - Selenium By selector support and related documentation, Support navigating to page instances in addition to classes
* github-profile:adjohnson916[Anders D. Johnson] - Doc improvements
* github-profile:azusa[Hiroyuki Ohnaka] - Doc improvements
* github-profile:bodiam[Erik Pragt] - Initial migration of the manual to AsciiDoctor
* github-profile:vijaybolleypally[Vijay Bolleypally] - Various fixes
* github-profile:pierre-hilt[Pierre Hilt] - `hasNot()` filtering
* github-profile:PoohSunny[Yotaro Takahashi] - Doc improvements
* github-profile:jochenberger[Jochen Berger] - Better error reporting when trying to set a nonexistent select option
* github-profile:matankatz[Matan Katz] - Support for setting the `forcelocal` flag for BrowserStack tunnel
* github-profile:victorparmar[Victor Parmar] - Add configuration option for including cause string representation in message of `WaitTimeoutException`
* github-profile:berardino[Berardino la Torre] - Fix incorrect delegation of waitFor() methods
* github-profile:madmas[Markus Schlichting] - Doc fixes
* github-profile:ahitrin[Andrey Hitrin] - Improvement to character replacing in report file names

== History

This page lists the high level changes between versions of Geb.

:numbered!:

=== {geb-version}

==== Improvements

* Non-ASCII word characters are not longer replaced in report file names. [issue:399[]]

==== Breaking changes

* Geb is now built with Groovy 2.4.3 and Spock 1.0-groovy-2.4.


=== 0.12.2

==== Fixes

* Fix incorrect delegation in variant of `waitFor()` that takes timeout and interval. [issue:395[]]
* Fix NPE on implicitly asserted statements that contain a safely navigated method call on null target. [issue:398[]]

=== 0.12.1

==== Fixes

* Change implementation of `waitFor()` method delegation so that IntelliJ does not complain that page and module classes supposedly need to implement it. [issue:391[]]
* Properly handle class attribute when it's passed to `$()` together with a css selector. [issue:390[]]

=== 0.12.0

==== New features

* Support for finding elements using Webdriver's [`By`][by-api] selectors. [issue:348[]]
* Support for navigating to page instances in addition to classes. [issue:310[]]
* Support for using page instances as `page` option value of window switching methods. [issue:352[]]
* Support for using page instances together with frame switching methods. [issue:354[]]
* Support for using page instances with `Navigator.click()` methods. [issue:355[]]
* Support for using page instances and lists of page instances as `page` option value of content templates. [issue:356[]]
* New `Navigator.module(Class&lt;? extends Module&gt;)` and `Navigable.module(Class&lt;? extends Module&gt;)`. [issue:312[]]
* New `Navigable.module(Module)` and `Navigable.module(Module)`. [issue:311[]]
* Support for using `interact {}` blocks in modules. [issue:364[]]
* Support page level `atCheckWaiting` configuration. [issue:287[]]
* `Navigator` elements can now also be filtered using `hasNot()` method. [issue:370[]]
* Custom implementation of `equals()` and `hashCode()` methods have been added to classes implementing `Navigator`. [issue:374[]]
* Support setting `forcelocal` flag for BrowserStack tunnel. [issue:385[]]
* Add configuration option for including cause string representation in message of `WaitTimeoutException`. [issue:386[]]

==== Improvements

* Using unrecognized content template parameters result in an `InvalidPageContent` exception to make catching typos in them easier. [issue:377[]]
* Improve error reporting when no at checkers pass if using multiple candidates for page switching. [issue:346[]]
* Don't unnecessarily lookup root element for every baseless element lookup using `$()` in context of `Navigable`. [issue:306[]]
* Attribute based searches are compiled to CSS selectors where possible. [issue:280[]]
* Attribute based searches using an id, class or name are performed using an appropriate `By` selector where possible. [issue:333[]]

==== Fixes

* Improved message thrown from Navigator.isDisabled() and Navigator.isReadOnly() when navigator does not contain a form element. [issue:345[]]
* Browser.verifyAtIfPresent() should fail for at checkers returning false when implicit assertions are disabled. [issue:357[]]
* Provide better error reporting when unexpected pages configuration is not a collection that contains classes which extend `Page`. [issue:270[]]
* Don't fail when creating a report and driver's screenshot taking method returns null. [issue:292[]]
* Classes that can define content should not throw custom exceptions from `propertyMissing()`. [issue:367[]]
* “At checkers” of pages passed to `withFrame()` methods are now verified. [issue:358[]]

==== Breaking changes

* `Page.toString()` now returns full page class name instead of its simple name.
* `MissingPropertyException` is thrown instead of `UnresolvablePropertyException` when content with a given name is not found on page or module.
* Geb is now built with Groovy 2.3.10 and Spock 1.0-groovy-2.3.

==== Deprecations

* `module(Class&lt;? extends Module&gt;, Navigator base)` available in content DSL has been deprecated in favour of `Navigator.module(Class&lt;? extends Module&gt;)` and will be removed in a future
 version of Geb.
* `module(Class&lt;? extends Module&gt;, Map args)` available in content DSL has been deprecated in favour of `Navigable.module(Module)` and will be removed in a future version of Geb.
* `module(Class&lt;? extends Module&gt;, Navigator base, Map args)` available in content DSL has been deprecated in favour of `Navigator.module(Module)` and will be removed in a future version of Geb.
* all variants of `moduleList()` method available in content DSL have been deprecated in favour of using `Navigator.module()` methods together with a `collect()` call and will be removed in a future
version of Geb, see <<repeating-content, chapter on using modules for repeating content>> for examples [issue:362[]]
* `isDisabled()`, `isEnabled()`, `isReadOnly()` and `isEditable()` methods of `Navigator` have been deprecated and will be removed in a future version of Geb. These methods are now available on the
new <<form-element, `FormElement`>> module class.

==== Project related changes

* User mailing list has moved to https://groups.google.com/d/forum/geb-user[Google Groups].
* The Book of Geb has been migrated to Asciidoctor and the examples have been made executable. [issue:350[]]

=== 0.10.0

==== New features

* New `css()` method on `Navigator` that allows to access CSS properties of elements. [issue:141[]]
* Added attribute based methods to relative content navigators such as next(), children() etc. [issue:299[]]
* Added signature that accepts `localIdentifier` to `BrowserStackDriverFactory.create`. [issue:332[]]
* Added <<content-dsl-to-wait, `toWait`>> content definition option which allows specifying that page transition happens asynchronously. [issue:134[]]
* Added support for explicitly specifying browser capabilities when using cloud browsers Gradle plugins. [issue:340[]]
* Added an overloaded `create()` method on cloud driver factories that allow specifying browser capabilities in a map and don't require a string capabilities specification. [issue:281[]]

==== Fixes

* Allow access to module properties from its content block. [issue:245[]]
* Support setting of elements for WebDriver implementations that return uppercase tag name. [issue:318[]]
* Use native binaries for running BrowserStack tunnel. [issue:326[]]
* Update BrowserStack support to use command-line arguments introduced in tunnel version 3.1. [issue:332[]]
* Fix PermGen memory leak when using groovy script backed configuration. [issue:335[]]
* Don't fail in `Browser.isAt()` if at check waiting is enabled and it times out. [issue:337[]]
* The value passed to `aliases` content option in documentation examples should be a String [issue:338[]]
* Added `$()` method on Navigator with all signatures of `find()`. [issue:321[]]
* `geb-saucelabs` plugin now uses a native version of SauceConnect. [issue:341[]]
* Don't modify the predicate map passed to link:api/geb/navigator/BasicLocator.html#find(Map%3CString,%20Object%3E,%20java.lang.String)["`Navigator.find(Map&lt;String, Object&gt;, String)`"]. [issue:339[]]
* Functional tests implemented using JUnit and Geb run twice in Grails 2.3+. [issue:314[]]
* Mention in the manual where snapshot artifacts can be downloaded from. [issue:305[]]
* Document that `withNewWindow()` and `withWindow()` switch page back to the original one. [issue:279[]]
* Fix selectors in documentation for manipulating checkboxes. [issue:268[]]

==== Project related changes

* Updated cucumber integration example to use `cucumber-jvm` instead of the now defunct `cuke4duke`. [issue:324[]]
* Setup CI for all of the example projects. [issue:188[]]
* Incorporate the example projects into the main build. [issue:189[]]
* Add a test crawling the site in search for broken links. [issue:327[]]
* Document the https://github.com/geb/geb/blob/master/RELEASING.md[release process]. [issue:325[]]

==== Breaking changes

* Use Groovy 2.3.6 to build Geb. [issue:330[]]
* Format of browser specification passed to `BrowserStackBrowserFactory.create()` and `SauceLabsBrowserFactory.create()` has changed to be a string in Java properties file format defining the required browser capabilities.
* `sauceConnect` configuration used with `geb-saucelabs` plugin should now point at a version of 'ci-sauce' artifact from 'com.saucelabs' group.

=== 0.9.3

==== New features

* Added `baseNavigatorWaiting` setting to prevent intermittent Firefox driver errors when creating base navigator. [issue:269[]]
* Page content classes including `Module` now implement `Navigator` interface [issue:181[]]
* Added some tests that guard performance by verifying which WebDriver commands are executed [issue:302[]]
* Added http://www.browserstack.com[BrowserStack] integration [issue:307[]]
* Added a shortcut to `Browser` for getting current url [issue:294[]]
* Verify pages at checker when passed as an option to open a new window via `withWindow()` and `withNewWindow()` [issue:278[]]

==== Fixes

* Ignore `atCheckWaiting` setting when checking for unexpected pages. [issue:267[]]
* Added missing range variants of find/$ methods. [issue:283[]]
* Migrated `UnableToLoadException` to java. [issue:263[]]
* Exception thrown when trying to set value on an invalid element (non form control). [issue:286[]]
* Support for jQuery methods like offset() and position() which return a native Javascript object. [issue:271[]]
* Finding elements when passing ids with spaces in the predicates map to the $() method. [issue:308[]]

==== Breaking changes

* Removed easyb support. [issue:277[]]
* `MissingMethodException` is now thrown when using shortcut for obtaining a navigator based on a control name and the returned navigator is empty. [issue:239[]]
* When using SauceLabs integration, the `allSauceTests` task was renamed to`allSauceLabsTests`
* When using SauceLabs integration, the `geb.sauce.browser` system property was renamed to `geb.saucelabs.browser`
* `Module` now implements `Navigator` instead of `Navigable` so `Navigator`'s methods can be called on it without having to first call `$()` to get the module's base `Navigator`.

==== Project related changes

* Documentation site has been migrated to http://ratpack.io[Ratpack]. [issue:261[]]
* Cross browser tests are now also executed using Safari driver [issue:276[]]
* Artifact snapshots are uploaded and gebish.org is updated after every successful build in CI [issue:295[]]
* Migrated continuous integration build to https://snap-ci.com/geb/geb/branch/master[Snap CI]
* Added a https://travis-ci.org/geb/geb[Travis CI build] that runs tests on submitted pull requests [issue:309[]]

=== 0.9.2

==== New features

* `page` and `close` options can be passed to `withWindow()` calls, see <<already-opened-windows, this manual section>> for more information.
* Unexpected pages can be specified to fail fast when performing “at” checks. This feature was contributed at a Hackergarten thanks to Andy Duncan. See <<unexpected-pages, this manual section>> for details. [issue:70[]]
* Support for running Geb using SauceLabs provided browsers, see <<cloud-browser-testing, this manual section>> for details.
* New link:api/geb/navigator/Navigator.html#isEnabled()[`isEnabled()`] and link:api/geb/navigator/Navigator.html#isEditable()[`isEditable()`] methods on `Navigator`.
* Support for ephemeral port allocation with Grails integration
* Compatibility with Grails 2.3

==== Fixes

* Default value of `close` option for `withNewWindow()` is set to `true` as specified in the documentation. [issue:258[]]

==== Breaking changes

* `isDisabled()` now throws `UnsupportedOperationException` if called on an `EmptyNavigator` or on a `Navigator` that contains anything else than a button, input, option, select or textarea.
* `isReadOnly()` now throws `UnsupportedOperationException` if called on an `EmptyNavigator` or on a `Navigator` that contains anything else than an input or a textarea.

=== 0.9.1

==== Breaking changes

* Explicitly calling `at()` with a page object will throw `UndefinedAtCheckerException` instead of silently passing if the page object does not define an at checker.
* Passing a page with no at checker to `click(List&lt;Class&lt;? extends Page&gt;&gt;)` or as one of the pages in `to` template option will throw `UndefinedAtCheckerException`.

==== New features

* Support for dealing with self-signed certificates in Download API using `SelfSignedCertificateHelper`. [issue:150[]]
* Connections created when using Download API can be configured globally using `defaultDownloadConfig` configuration option.
* New `atCheckWaiting` configuration option allowing to implictly wrap “at” checkers in `waitFor` calls. [issue:253[]]

==== Fixes

* `containsWord()` and `iContainsWord()` now return expected results when matching against text that contains spaces [issue:254[]]
* `has(Map&lt;String, Object&gt; predicates, String selector)` and `has(Map&lt;String, Object&gt; predicates)` were added to Navigator for consistency with `find()` and `filter()` [issue:256[]]
* Also catch WaitTimeoutException when page verification has failed following a `click()` call [issue:255[]]
* `not(Map&lt;String, Object&gt; predicates, String selector)` and `not(Map&lt;String, Object&gt; predicates)` were added to Navigator for consistency with `find()` and `filter()` [issue:257[]]
* Make sure that `NullPointerException` is not thrown for incorrect driver implementations of getting current url without previously driving the browser to a url [issue:291[]]

=== 0.9.0

==== New features

* New `via()` method that behaves the same way as `to()` behaved previously - it sets the page on the browser and does not verify the at checker of that page[issue:249[]].
* It is now possible to provide your own [`Navigator`][navigator-api] implementations by specifying a custom link:api/geb/navigator/factory/NavigatorFactory.html[`NavigatorFactory`], see <<navigator-factory, this manual section>> for more information [issue:96[]].
* New variants of `withFrame()` method that allow to switch into frame context and change the page in one go and also automatically change it back to the original page after the call, see [switching pages and frames at once][switch-frame-and-page] in the manual [issue:213[]].
* `wait`, `page` and `close` options can be passed to `withNewWindow()` calls, see <<newly-opened-windows, this manual section>> for more information [issue:167[]].
* Improved message of UnresolvablePropertyException to include a hint about forgetting to import the class [issue:240[]].
* Improved signature of `Browser.at()` and `Browser.to()` to return the exact type of the page that was asserted to be at / was navigated to.
* link:api/geb/report/ReportingListener.html[`ReportingListener`] objects can be registered to observe reporting (see: <<listening-to-reporting, this manual section>>)

==== Fixes

* Fixed an issue where waitFor would throw a WaitTimeoutException even if the last evaluation before timeout returned a truthy value [issue:215[]].
* Fixed taking screenshots for reporting when the browser is not on a HTML page (e.g. XML file) [issue:126[]].
* Return the last evaluation value for a `(wait: true, required: false)` content instead of always returning null [issue:216[]].
* `isAt()` behaves the same as `at()` in regards to updating the browser's page instance to the given page type if its at checker is successful [issue:227[]].
* Handling of `select` elements has been reworked to be far more efficient [issue:229[]].
* Modules support accessing base attributes' values using @attributeName notation [issue:237[]].
* Use of text matchers in module base definitions is supported [issue:241[]].
* Reading of textareas have been updated so that the current value of the text field is returned, instead of the initial [issue:174[]].

==== Breaking changes

* `to(Class&lt;? extends Page&gt;)` method now changes the page on the browser and verifies the at checker of that page in one method call [issue:1[]], [issue:249[]]; use `via()` if you need the old behaviour
* `getAttribute(String)` on `Navigator` now returns `null` for boolean attributes that are not present.
* `at()` and `to()` methods on `Browser` now return a page instance if they succeed and `via()` method always returns a page instance [issue:217[]].
* `withFrame()` calls that don't take a page argument now change the browser page to what it was before the call, after the call [issue:222[]].
* due to performance improvements duplicate elements are not removed when creating new `Navigator`s anymore; the new `unique()` method on `Navigator` can be used to remove duplicates if needed [issue:223[]].
* `at(Page)` and `isAt(Page)` methods on `Browser` have been removed as they were inconsistent with the rest of the API [issue:242[]].
* Navigator's `click(Class&lt;? extends Page&gt;)` and `to:` content option now verify page after switching to the new one to stay consistent with the new behaviour of `to(Class&lt;? extends Page&gt;)` [issue:250[]].
* Reading an attribute that is not set on a navigator now returns an empty string across all drivers [issue:251[]].

=== 0.7.2

==== Fixes

* Further fixes for Java 7 [issue:211[]].

=== 0.7.1

==== New features

* Geb is now built with Groovy 1.8.6. This was forced to resolve [issue:194[]].

==== Fixes

* `startsWith()`, `contains()` etc. now work for selecting via element text now works for multiline (i.e. `&lt;br/&gt;`) text [issue:202[]]
* Geb now works with Java 7 [issue:194[]].

=== 0.7.0

==== New features

* Added support for indexes and ranges in `moduleList()` method
* Form control shortcuts now also work on page and module content
* Custom timeout message for `waitFor()` calls
* Navigators can be composed also from content
* Closure expressions passed to `waitFor()` calls are now transformed so that every statement in them is asserted - this provides better reporting on `waitFor()` timeouts.
* `at` closure properties of Page classes are now transformed so that every statement in them is asserted - this provides better reporting on failed at checks
* new `isAt()` method on Browser that behaves like `at()` used to behave before, i.e. does not throw AssertionError but returns `false` if at checking fails
* `withAlert()` and `withConfirm()` now accept a `wait` option and the possible values are the same as for waiting content

==== Breaking changes

* `click()` now instructs the browser to click *only on the first* element the navigator has matched
* All `click()` method variants return the reciever
* Content definitions with `required: false, wait: true` return `null` and do not throw `WaitTimeoutException` if the timeout expires
* Assignment statements are not allowed anymore in closure expressions passed to `waitFor()` calls
* `at()` now throws AssertionException if at checking fails instead of returning false

=== 0.6.3

==== New features

* Compatibility with Spock 0.6

=== 0.6.2

==== New features

* New `interact()` function for mouse and keyboard actions which delegates to the WebDriver Actions class
* New `moduleList()` function for repeating content
* New `withFrame()` method for working with frames
* New `withWindow()` and `withNewWindow()` methods for working with multiple windows
* Added `getCurrentWindow()` and `getAvailableWindows()` methods to browser that delegate to the underlying driver instance
* Content aliasing is now possible using `aliases` parameter in content DSL
* If config script is not found a config class will be used if there is any - this is usefull if you run test using Geb from IDE
* Drivers are now cached across the whole JVM, which avoids the browser startup cost in some situations
* Added config option to disable quitting of cached browsers on JVM shutdown

==== Breaking changes

* The `Page.convertToPath()` function is now responsible for adding a prefix slash if required (i.e. it's not added implicitly in `Page.getPageUrl()`) [GEB-139].
* Unchecked checkboxes now report their value as `false` instead of null

=== 0.6.1

==== New features

* Compatibility with at least Selenium 2.9.0 (version 0.6.0 of Geb did not work with Selenium 2.5.0 and up)
* Attempting to set a select to a value that it does not contain now throws an exception
* The waiting algorithm is now time based instead of number of retries based, which is better for blocks that are not near instant
* Better support for working with already instantiated pages

==== Breaking changes

* Using `&lt;select&gt;` elements with Geb now requires an explicit dependency on an extra WebDriver jar (see <<installation-usage, the section on installation for more info>>)
* The `Navigator` `classes()` method now returns a `List` (instead of `Set`) and guarantees that it will be sorted alphabetically

=== 0.6

==== New features

* selenium-common is now a 'provided' scoped dependency of Geb
* Radio buttons can be selected with their label text as well as their value attribute.
* Select options can be selected with their text as well as their value attribute.
* `Navigator.getAttribute` returns `null` rather than the empty string when an attribute is not found.
* The `jquery` property on `Navigator` now returns whatever the jQuery method called on it returns.
* All waitFor clauses now treat exceptions raised in the condition as an evaluation failure, instead of propagating the exception
* Content can be defined with `wait: true` to make Geb implicitly wait for it when it is requested
* Screenshots are now taken when reporting for all drivers that implement the `TakesScreenshot` interface (which is nearly all)
* Added `BindingUpdater` class that can manage a groovy script binding for use with Geb
* Added `quit()` and `close()` methods to browser that delegate to the underlying driver instance
* `geb.Browser.drive()` methods now return the used `Browser` instance
* The underlying WebElements of a Navigator are now retrievable
* Added $() methods that take one or more Navigator or WebElement objects and returns a new Navigator composed of these objects
* Added Direct Download API which can be used for directly downloading content (PDFs, CSVs etc.) into your Geb program (not via the browser)
* Introduced new configuration mechanism for more flexible and environment sensitive configuration of Geb (e.g. driver implementation, base url)
* Default wait timeout and retry interval is now configurable, and can now also use user configuration presets (e.g. quick, slow)
* Added a “build adapter” mechanism, making it easier for build systems to take control of relevant configuration
* The JUnit 3 integration now includes the test method name in the automatically generated reports
* The reporting support has been rewritten, making it much friendlier to use outside of testing
* Added the TestNG support (contributed by Alexander Zolotov)
* Added the `height`, `width`, `x` and `y` properties to navigator objects and modules

==== Breaking changes

* Raised minimum Groovy version to 1.7
* All failed waitFor clauses now throw a `geb.waiting.WaitTimeoutException` instead of `AssertionError`
* Upgraded minimum version requirement of WebDriver to 2.0rc1
* The `onLoad()` and `onUnload()` page methods both have changed their return types from `def` to `void`
* The Grails specific testing subclasses have been REMOVED. Use the direct equivalent instead (e.g `geb.spock.GebReportingSpec` instead of `grails.plugin.geb.GebSpec`)
* The Grails plugin no longer depends on the test integration modules, you need to depend on the one you want manually
* The `getBaseUrl()` method from testing subclasses has been removed, use the configuration mechanism
* Inputs with no value now report their value as an empty string instead of `null`
* Select elements that are not multiple select enabled no longer report their value as a 1 element list, but now as the value of the selected element (if no selection, `null` is returned)

=== 0.5.1

* Fixed problem with incorrectly compiled specs and the geb grails module

=== 0.5

==== New features

* Navigator objects now implement the Groovy truth (empty == false, non empty == true)
* Introduced “js” short notation
* Added “{easyb}” support (`geb-easyb`) and Grails support
* Page change listening support through `geb.PageChangeListener`
* `waitFor()` methods added, making dealing with dynamic pages easier
* Support for `alert()` and `confirm()` dialogs
* Added jQuery integration
* Reporting integration classes (e.g. GebReportingSpec) now save a screenshot if using the FirefoxDriver
* Added `displayed` property to navigator objects for determining visibility
* Added `find` as an alias for `$` (e.g. `find(&quot;div.section&quot;)`)
* Browser objects now implement the `page(List&lt;Class&gt;)` method that sets the page to the first type whose at-checker matches the page
* The click() methods that take one or more page classes are now available on `Navigator` objects
* Added page lifecycle methods `onLoad()`/`onUnload()`

==== Breaking changes

* Exceptions raised in `drive()` blocks are no longer wrapped with `DriveException`
* the `at(Class pageClass)` method no longer requires the existing page instance to be of that class (page will be updated if the given type matches)

=== 0.4

*Initial Public Release*

:numbered:
